[package]
name = "zht-proto"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Protobuf message definitions for ZHT"

[dependencies]
prost = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true }

[build-dependencies]
prost-build = "0.13"
